#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

xrdb merge $HOME/xresources/catppuccin &

feh --bg-fill ~/bg.png &

bspc monitor $(xrandr | grep -w connected  | awk -F'[ \+]' '{print $1}') -d 1 2 3 4 5 &

bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 1
bspc config borderless_monocle true

bspc config gapless_monocle false
bspc config window_gap 20
bspc config split_ratio 0.50

bspc rule -a * state=tiled

xsetroot -cursor_name left_ptr
xinput set-prop 'MSFT0001:00 04F3:3140 Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'MSFT0001:00 04F3:3140 Touchpad' 'libinput Natural Scrolling Enabled' 1

ibus restart &
ibus-daemon
picom &

~/.local/bin/eww daemon &
~/.config/polybar/launch.sh &
